<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHj84ghz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHj84ghz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHj84ghz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHj84ghz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHj84ghz\appProdProjectContainer([
    'container.build_hash' => 'Hj84ghz',
    'container.build_id' => 'ba46ceba',
    'container.build_time' => 1635627153,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHj84ghz');
