<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG2lf8d5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG2lf8d5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerG2lf8d5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerG2lf8d5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerG2lf8d5\appProdProjectContainer([
    'container.build_hash' => 'G2lf8d5',
    'container.build_id' => 'c7b825d2',
    'container.build_time' => 1635628366,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG2lf8d5');
